# Generated by Django 2.2 on 2019-04-26 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop', '0004_auto_20190423_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('created', 'created'), ('paid', 'paid'), ('shipped', 'shipped'), ('refunded', 'refunded')], default='created', max_length=200)),
                ('shipping_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Eshop.Cart')),
            ],
        ),
    ]
