# Generated by Django 2.2 on 2019-04-27 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop', '0005_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('straat', models.CharField(max_length=200)),
                ('nr', models.CharField(max_length=200)),
                ('stad', models.CharField(max_length=200)),
                ('postcode', models.CharField(max_length=200)),
                ('land', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='billingAdress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Eshop.Adress'),
        ),
    ]
