# Generated by Django 2.2 on 2019-04-28 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop', '0006_auto_20190427_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='korting',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
    ]
