# Generated by Django 2.2 on 2019-04-28 11:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop', '0007_product_korting'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='timestamp',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
